// <auto-generated />
using System;
using HepsiSln.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HepsiSln.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129085030_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HepsiSln.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(3472),
                            IsDeleted = false,
                            Name = "Music & Tools"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(3478),
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(3481),
                            IsDeleted = false,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(5327),
                            IsDeleted = false,
                            Name = "Elektrik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(5328),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(5330),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 139, DateTimeKind.Local).AddTicks(5331),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 2,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 140, DateTimeKind.Local).AddTicks(7134),
                            Description = "Yazın kulu veniam çorba dolores sit açılmadan odio aut rem.\nMıknatıslı gül quia quia.\nİnventore et ekşili laboriosam çobanın ab aperiam.\nUllam quaerat quia ki uzattı eius dergi dicta eaque gördüm.\nCezbelendi ut sıla iure.",
                            IsDeleted = false,
                            Title = "Çünkü."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 140, DateTimeKind.Local).AddTicks(7411),
                            Description = "Dağılımı exercitationem çorba adresini çünkü doğru aperiam masaya inventore sit.\nMagnam aut velit non sıradanlıktan sandalye.\nNon kutusu iusto.\nHesap şafak enim.\nOdio quia ea exercitationem veritatis öyle quia et masanın.",
                            IsDeleted = true,
                            Title = "Reprehenderit qui."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 140, DateTimeKind.Local).AddTicks(7509),
                            Description = "Yazın sit non olduğu için quia modi çorba totam praesentium.\nMakinesi olduğu salladı ullam labore sokaklarda cesurca.\nVeniam dışarı ratione.\nİure sed koştum duyulmamış beğendim amet sevindi.\nEnim de explicabo otobüs masaya cesurca.",
                            IsDeleted = false,
                            Title = "Velit."
                        });
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 142, DateTimeKind.Local).AddTicks(3466),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 3.278124573024010m,
                            IsDeleted = false,
                            Price = 403.27m,
                            Title = "Rustic Concrete Keyboard"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 29, 11, 50, 30, 142, DateTimeKind.Local).AddTicks(3507),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 1.763900033459610m,
                            IsDeleted = false,
                            Price = 851.82m,
                            Title = "Incredible Steel Sausages"
                        });
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategorytId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategorytId");

                    b.HasIndex("CategorytId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Detail", b =>
                {
                    b.HasOne("HepsiSln.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Product", b =>
                {
                    b.HasOne("HepsiSln.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("HepsiSln.Domain.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategorytId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HepsiSln.Domain.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("HepsiSln.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
